### ISSUE TITLE
When an experimenter submits an experiment, there should be a configuration file associated with their submission to simplify operator actions.

### ISSUE THREAD

**Issue by 17jhagan** [DiscoverCCRI/DISCOVER-Experiment-Template#1]
Last week (5/24), we mentioned that a configuration file should be present in the experiment repository that a user submits. The goal of this config file would be to enable some helpful automation within our DISCOVER infrastructure down the line when experiments are submitted.

**Comment by cjb873** [comment]
![Screenshot 2023-05-31 at 11 19 32 AM](https://github.com/DiscoverCCRI/DISCOVER-Experiment-Template/assets/102448637/6fd92f88-fffd-4789-b9b3-c6d82f56226c)

**Comment by 17jhagan** [comment]
Let's consider how the experiment resource definition menu could be used to generate this file for the server. We may need multiple types of configuration files in this, so we should evaluate at what stage would certain config files be helpful.

**Comment by 17jhagan** [comment]
Closing this issue; we decided to auto-generate the config file when an experimenter creates an experiment.
